### PR TITLE
update again, check for changes you don't want.

### PR DESCRIPTION
**Pull request by meelock**
I changed a lot of stuff, please check the file for inconsistencies!

### CODE REVIEW

**Comment by Nedelosk** [comment]
Thank you very much!
The only thinks that I don't want are:
module.size.large.name=Enhanced
module.size.medium.name=Normal
The rest is very great

**Comment by meelock** [comment]
what should those be? medium and large are just... rather bland... any suggestions?

**Comment by Nedelosk** [comment]
Large and medium are sizes of modules and I don't think that a size of a module is enhanced.

**Comment by meelock** [comment]
kk, I was just thinking that it would be cool if it wasn't just size based as I don't think (as far as I know) the larger modules take up any more slots, only more complexity.

**Comment by Nedelosk** [comment]
After thinking over it I think Enhanced and Normal are the best choice

**Comment by meelock** [comment]
anything else? (enhanced and normal still don't exactly work, so I was wanting your input.)

**Comment by meelock** [comment]
gg! all looks well.

**Pull request merged**
